### ISSUE TITLE
Support for disabled by default features?

### ISSUE THREAD

**Issue by acomminos** [w3c/webappsec-permissions-policy#412]
Currently, permissions policy doesn't allow for features to be disabled by default (i.e. have a default allowlist of "none").

Adding support for this would be tremendously valuable for features such as the [JS Self-Profiling API](https://github.com/WICG/js-self-profiling), which may require extra metadata to be collected by the user agent if the feature is going to be used on a page. Having a default allowlist of "none" for the feature would ensure that no extra overhead is incurred when pages don't perform profiling.

Curious about folks' thoughts on this, as well as whether or not permissions policy is a right fit for this use case (we expect so, considering this is a powerful feature that sites will likely want to control frame inheritance of).

Thanks!

(cc @yoavweiss)

**Comment by annevk** [comment]
Permissions Policy is good for features that everyone wants, but the parent has to delegate before children get it. I don't think it works well when there's a cost as now the parent gets to decide for the child whether it will incur a cost, which might be detrimental to it in some way. Document Policy seems better as the child will have to consent in order to get it.

**Comment by acomminos** [comment]
Thanks for the context @annevk -- it does indeed look like Document Policy is a better fit here, aside from the inability for parent frames to restrict features in subframes (though it's not nearly as critical for our use case). Is a mechanism to facilitate that in scope for Document Policy?

**Comment by annevk** [comment]
Document Policy does have that ability (for consenting children).

**Comment by acomminos** [comment]
Ah perfect, thank you for the pointers! Closing this.
